- .travis.yml
- tests/test_data_integrity.py
- tests/test_db_validity.py
> Add travis CI testing

- Dockerfile
- Jenkinsfile
- requirements.txt
- setup.py
- whotracksme/website/serve.py
I replaced the slow `http.server` from standard library by `sanic` to serve the `_site` files. It's much faster now.
> Implement a faster http server (sanic)

- blog/generating_adblocker_filters.md
- setup.py
• Take into account comments
• Fix code snippets to use the new package format
> Update post “Generating Ad-Blocker filters from whotracks.me data”.

- deploy_to_s3.py
Should make page loads faster.
> Increase page cache time

- README.md
- RIGHT_TO_AMEND.md
- blog/tracker_categories.md
- requirements.txt
- templates/base.html
- templates/not-found.html
- templates/tracker-not-found.html
- templates/website-not-found.html
- whotracksme/data/loader.py
- whotracksme/main.py
- whotracksme/qa/todo.py
- whotracksme/qa/utils.py
- whotracksme/website/templates.py
> Issue fixes and QA utils

- blog/update_apr_2018.md
- whotracksme/website/plotting/sankey.py
The sankey plot on Sites with many trackers does not render properly - adjusting height.
> Quick Sankey Fix

- whotracksme/data/assets/trackerdb.sql
Rebase of #73 to fix merge issues.
> Tracker db march

- Jenkinsfile
Use tags to trigger production builds on Jenkins.
> Build production for tags.

- blog/tracker-tax.md
> text formatting

- whotracksme/website/build/trackers.py
This handles the formatting of reach metrics in third party profiles.
> Formatted tracker reach metrics

- whotracksme/data/loader.py
- whotracksme/website/build/trackers.py
Now you can load data only for a specific region (depending on availability) e.g.
```global_data = DataSource(region="global")```
> Added region param to DataSource

- requirements-dev.txt
- requirements.txt
- setup.py
> Move requests requirement

- requirements-dev.txt
- whotracksme/website/build/companies.py
- whotracksme/website/plotting/colors.py
- whotracksme/website/plotting/companies.py
- whotracksme/website/plotting/trackers.py
- whotracksme/website/plotting/utils.py
Fixes #122 
No worries if you actually don't want to update to latest plotly. 
Did a spot check and things look right to me. Here's a few screenshots.
> Update to latest plotly

- whotracksme/website/build/data.py
- whotracksme/website/builder.py
Present overview stats for each tracker in json format.
> Basic API for tracker overview stats.

- whotracksme/website/build/data.py
As old site_reach is null for the latest month.
> Remove site_reach key from api data

- whotracksme/data/loader.py
- whotracksme/website/build/data.py
- whotracksme/website/builder.py
Add extra data to trackers API:
* Reach and site reach time series
* Presence on site types.
* Company name.
> API Additions

- whotracksme/website/build/data.py
This PR adds a folder to the data directory which serves the data to the API.  The folder contains tracker data with `ghostery_id` as the filename.
> Add folder to API

- whotracksme/website/build/data.py
- Added tracking type to the Ghostery API files so that it's accessible in the API for our new product
> Add tracking type to Ghostery files for the API

- blog/adblockers_performance_study.md
> performance study: amend DuckDuckGo's description

- whotracksme/website/build/data.py
- whotracksme/website/builder.py
Expose website summary stats via api at `data/sites/global/hostname.json`.
> Add website API.

- Jenkinsfile
Jenkins needs to fetch datasets from Amazon S3
> jenkins: new stage - Download Datasets

- .github/workflows/test.yml
New datasets uploaded to s3://data.whotracks.me/2021-05
> Datasets 2021-05

- .github/workflows/test.yml
New datasets uploaded to s3://data.whotracks.me/2021-06
> Datasets 2021-06

- blog/static_site_visualization.md
- whotracksme/data/Readme.md
- whotracksme/website/build/blog.py
- whotracksme/website/build/companies.py
- whotracksme/website/plotting/colors.py
- whotracksme/website/plotting/companies.py
- whotracksme/website/plotting/plots.py
- whotracksme/website/plotting/sankey.py
- whotracksme/website/plotting/trackers.py
- whotracksme/website/plotting/utils.py
* improve naming consistency
* typos fixed
> Improve naming consistency

- .github/workflows/test.yml
- .tool-versions
- Dockerfile
- README.md
- setup.py
We need to upgrade the Python version to at least 3.7 to fix this issue:
https://github.com/whotracksme/whotracks.me/pull/254#issuecomment-983068042
Fixes #254
> bump python to 3.7

- static/scss/custom.scss
- templates/components/footer.html
- templates/imprint.html
- templates/privacy-policy.html
- whotracksme/website/build/home.py
- whotracksme/website/builder.py
* Update privacy policy
* Move imprint to separate page
> Update privacy policy

- deploy_to_s3.py
New option "--fast-website-update" to speed up deploying the website when it is not a monthly release. It will skip the
upload of the generated files.
> New option "--fast-website-update"

- blog/adblockers_performance_study.md
Does not change any data about measurements or about the conclusions.
> Apply update to blog

- tests/test_db_integrity.py
- tests/test_db_validity.py
Fixes https://github.com/whotracksme/whotracks.me/issues/345
> Make the tests pass again.
